### ISSUE TITLE
I can't select hubs for search after connecting to specific HUBs

### ISSUE THREAD

**Issue by Zamana** [airdcpp-web/airdcpp-webclient#373] opened 2020-11-08 13:45 UTC
### Current UI and client versions:
Application version: **AirDC++w 2.9.0 amd64**
Web UI version: **2.9.0-beta.8**
Web UI build date: **September 15, 2020 2:17 PM**
API version: **1**
API feature level: **5**

### Browsers: 
**Safari** (Version 14.0 (15610.1.28.1.9, 15610)
**Brave** (Version 1.16.72 Chromium: 86.0.4240.183 (Official Build) (x86_64))
**Chrome** (Version 86.0.4240.183 (Official Build) (x86_64))

### Operating system:
**FreeNAS 11.3-U5 (FreeBSD 11.3-RELEASE-p14)**

### Steps to reproduce the issue:
Starting in November, 7 2020, after connecting to one of these two hubs, the selector hub at the search page stops to work (it became irresponsive to clicks):

- White Nights of St. Petersburg: nmdcs://piter.feardc.net:411
- Lithuania DC++: dchub://dchub.lt

In the case of Lithuania DC++ is a little worse, because after connecting to this hub, when I click in the Hubs button, browsers renders a blank page.

It seems an UI issue. No errors seems to be logged.

**Comment by maksis** [comment] 2020-11-08 14:17
This should be confirmed with the latest UI version

**Comment by Zamana** [comment] 2020-11-08 17:34
Hi!

After successfully updating to the latest UI version (2.9.0, no beta...), the issue with the HUB "White Nights of St. Petersburg: nmdcs://piter.feardc.net:411" is gone.

By other hand, the issue with the HUB "Lithuania DC++: dchub://dchub.lt" continue. This time it raises the following error message at the browser, just after the login or after clicking at the Hubs icon:

**Web UI has crashed with the following error: "URIError: URI error"

Please submit a bug report with the requested information (and the error message above) at the issue tracker.**

**Comment by maksis** [comment] 2020-11-08 17:36
I can reproduce this, seems to be related to magnet links in the chat

**Comment by maksis** [comment] 2020-11-08 18:03
Fixed in the latest beta UI

**Comment by maksis** [comment] 2020-11-08 19:03
Sounds like there were two separate issues (the crash was fixed, the other one is still happening for @Zamana )

**Comment by Zamana** [comment] 2020-11-08 19:06
I should have opened 2 separate issues, but I did think that they were related.

Sorry.

**Comment by Zamana** [comment] 2020-11-14 13:05
Application version: AirDC++w 2.10.0b-65-g6518 amd64
Web UI version: 2.10.0-beta.2

I enabled the developer tool/console in Chrome, and got this:

`i18next.js:22 i18next::backendConnector: loaded namespace main for language en Object
i18next.js:22 i18next: languageChanged en-US
i18next.js:22 i18next: initialized Object
LoginGuardEffect.ts:21 UI: Redirecting to login page
SocketLogger.js:41 Starting socket connect
SocketLogger.js:41 Socket connected
SocketLogger.js:41 Login succeed
Notifications.tsx:89 [Deprecation] The Notification API may no longer be used from insecure origins. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
t.componentDidMount @ Notifications.tsx:89
RSS.tsx:106 RSS: no cached feed https://airdcpp-web.github.io/feed.xml
utils.ts:40 RSS feed received https://airdcpp-web.github.io/feed.xml
popup.js:1203 Popup: Popup does not fit within the boundaries of the viewport <span class=​"options popup trigger">​…​</span>​
error @ popup.js:1203
popup.js:926 Popup: Popup does not fit within the boundaries of the viewport <span class=​"options popup trigger">​…​</span>​
position @ popup.js:926
popup.js:926 Popup: Popup does not fit within the boundaries of the viewport <span class=​"options popup trigger">​…​</span>​
position @ popup.js:926`

So it's still happening

**Comment by maksis** [comment] 2020-11-15 19:54
> popup.js:926 Popup: Popup does not fit within the boundaries of the viewport <span class=​"options popup trigger">​…​</span>​
position @ popup.js:926

Do those lines only appear when the issue happens? Those may also be caused by some other popup so checking the message times would be good too (you may need to enable timestamps from the console settings).

**Comment by Zamana** [comment] 2020-11-16 14:42
Yes. Those lines appears only when I'm unable to select hubs for search.

Everything was working fine, and suddenly the error was triggered after I connect to this hub:

adcs://novosibirsk.dc-dev.club:7111

Here is the console output:

```
i18next.js:22 i18next::backendConnector: loaded namespace main for language en Object
i18next.js:22 i18next: languageChanged en-US
i18next.js:22 i18next: initialized Object
LoginGuardEffect.ts:21 UI: Redirecting to login page
SocketLogger.js:41 Starting socket connect
SocketLogger.js:41 Socket connected
SocketLogger.js:41 Login succeed
Notifications.tsx:89 [Deprecation] The Notification API may no longer be used from insecure origins. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
t.componentDidMount @ Notifications.tsx:89
RSS.tsx:106 RSS: no cached feed https://airdcpp-web.github.io/feed.xml
utils.ts:40 RSS feed received https://airdcpp-web.github.io/feed.xml
events.js:46 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 hub_counts_updated12 listeners added. Use emitter.setMaxListeners() to increase limit
    at u (http://airdc.local:5600/js/main.da431d81bea3e2467234.entry.js:62:1905735)
    at A.addListener (http://airdc.local:5600/js/main.da431d81bea3e2467234.entry.js:62:1908017)
    at Object.addListener (http://airdc.local:5600/js/main.da431d81bea3e2467234.entry.js:1:12776)
    at Object.e.addSocketListener (http://airdc.local:5600/js/main.da431d81bea3e2467234.entry.js:57:33325)
    at http://airdc.local:5600/js/hubs.27d9a154794af2b95976.chunk.js:1:8336
    at Ms (http://airdc.local:5600/js/main.da431d81bea3e2467234.entry.js:86:104244)
    at t.unstable_runWithPriority (http://airdc.local:5600/js/main.da431d81bea3e2467234.entry.js:94:3768)
    at Go (http://airdc.local:5600/js/main.da431d81bea3e2467234.entry.js:86:44549)
    at Is (http://airdc.local:5600/js/main.da431d81bea3e2467234.entry.js:86:103707)
    at ds (http://airdc.local:5600/js/main.da431d81bea3e2467234.entry.js:86:95008)
u @ events.js:46
A.addListener @ events.js:227
addListener @ SocketSubscriptionHandler.js:115
e.addSocketListener @ SocketSubscriptionDecorator.tsx:49
(anonymous) @ HubFooter.tsx:50
Ms @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Go @ react-dom.production.min.js:122
Is @ react-dom.production.min.js:261
ds @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Go @ react-dom.production.min.js:122
Lo @ react-dom.production.min.js:123
Po @ react-dom.production.min.js:122
As @ react-dom.production.min.js:237
Ea @ react-dom.production.min.js:170
(anonymous) @ ChatLayout.tsx:73
i @ PublisherMethods.js:52
a.emit @ index.js:116
t.trigger @ PublisherMethods.js:71
a @ MessageStoreDecorator.ts:39
_onChatMessage @ MessageStoreDecorator.ts:44
A.emit @ events.js:158
handleMessage @ SocketSubscriptionHandler.js:160
E @ SocketBase.js:79
popup.js:1203 Popup: Popup does not fit within the boundaries of the viewport <span class=​"options popup trigger">​…​</span>​
error @ popup.js:1203
position @ popup.js:926
position @ popup.js:916
position @ popup.js:916
position @ popup.js:916
position @ popup.js:916
position @ popup.js:916
position @ popup.js:916
position @ popup.js:916
position @ popup.js:916
position @ popup.js:916
position @ popup.js:916
position @ popup.js:916
position @ popup.js:916
position @ popup.js:916
position @ popup.js:916
position @ popup.js:916
show @ popup.js:345
invoke @ popup.js:1294
(anonymous) @ popup.js:1316
each @ jquery.js:381
each @ jquery.js:203
e.fn.popup @ popup.js:49
i.show @ Popup.tsx:147
(anonymous) @ Popup.tsx:46
Ms @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Go @ react-dom.production.min.js:122
Is @ react-dom.production.min.js:261
ds @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Go @ react-dom.production.min.js:122
Lo @ react-dom.production.min.js:123
Po @ react-dom.production.min.js:122
Fe @ react-dom.production.min.js:292
Vt @ react-dom.production.min.js:73
Show 7 more frames
```

**Comment by maksis** [comment] 2020-11-16 14:46
The message would suggest that it's related to the browser window size and the number of hubs in the list. Does the number of connected hubs make any difference? It shouldn't be related to any individual hub in such case.

**Comment by maksis** [comment] 2020-11-16 16:58
Could you try if this still happens with Web UI 2.10.0-beta.4?

**Comment by Zamana** [comment] 2020-11-16 18:10
Yes. Those 

> The message would suggest that it's related to the browser window size and the number of hubs in the list. Does the number of connected hubs make any difference? It shouldn't be related to any individual hub in such case.

Good point.

The issue does not occur when I'm connected at a maximum of 7 hubs.

**Comment by Zamana** [comment] 2020-11-16 18:34
> Could you try if this still happens with Web UI 2.10.0-beta.4?

With beta.4 the issue seems solved.

I saw that you changed the UI in order to separate the hubs list from the size limits...

Thanks!

**Closed** 2020-11-16 18:35 UTC
Labels: bug
