### ISSUE TITLE
Reverse proxy with Nginx (not an issue, might be helpful to someone)

### ISSUE THREAD

**Issue by Pauligrinder** [airdcpp-web/airdcpp-webclient#232] opened 2017-05-10 06:56 UTC
Hey!

I noticed that your website has information on how to set up a reverse proxy for Airdcpp using nginx, but that guide didn't work for me. All I got using that was a white page. So I read about the sockets etc. in the api documentation and figured out how to get it to work. Here's a snippet from my nginx.conf, feel free to use it any way you like:

```
location /airdcpp
        {
                proxy_pass http://127.0.0.1:5600/;
                gzip_types text/plain application/javascript;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_redirect off;
                proxy_set_header        Host            $host;
                proxy_set_header        X-Real-IP       $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        }

location /airdcpp/api/v1
        {
                proxy_pass http://127.0.0.1:5600/api/v1;
                gzip_types text/plain application/javascript;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_redirect off;
                proxy_set_header        Host            $host;
                proxy_set_header        X-Real-IP       $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        }
```

Some of the parameters are probably not needed, but it works this way so I can't be bothered removing unneeded ones. The point here is that /api/v1/ also needs to be proxied, otherwise the webclient can't connect to the socket :)
It might be a good idea to use the https-endpoints of airdcpp (change port to 5601 or whatever you defined + http -> https), but I've already set up https in nginx and the trafic already goes through that anyway. And my connection doesn't need to be encrypted when I'm using it at home.

**Comment by maksis** [comment] 2017-05-10 07:15
That's surprising, since I'm using the example config as it is. Do you have other config in nginx that might affect the app (such as basic auth being used)?

**Comment by u2hub** [comment] 2017-05-11 13:15
The above seems to be related to the "Authentication failed: Cannot connect to the server" error, which had been declared as solved here >> https://github.com/airdcpp-web/airdcpp-webclient/issues/205

Using CTRL+SHIFT+J and Google Chrome Version 57.0.2987.133

The following socket error does not allow you to connect.

main.7dd9190….entry.js:46236 Starting socket connect
SocketBase.js:190 WebSocket connection to 'ws://www.mywebsite.com/api/v1/' failed: Error during WebSocket handshake: Unexpected response code: 400
e @ SocketBase.js:190
(anonymous) @ SocketBase.js:221
D @ SocketBase.js:219
connect @ SocketBase.js:264
(anonymous) @ LoginActions.js:44
n @ PublisherMethods.js:54
o.emit @ index.js:139
t.trigger @ PublisherMethods.js:73
e @ main.7dd9190….entry.js:85905
onSubmit @ Login.jsx:106
_onKeyDown @ Login.jsx:93
i @ ReactErrorUtils.js:28
a @ EventPluginUtils.js:87
s @ EventPluginUtils.js:110
p @ EventPluginHub.js:43
h @ EventPluginHub.js:54
i @ forEachAccumulated.js:26
processEventQueue @ EventPluginHub.js:257
i @ main.7dd9190….entry.js:72924
handleTopLevel @ ReactEventEmitterMixin.js:30
r @ ReactEventListener.js:74
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:64
r @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:149
main.7dd9190….entry.js:46236 Connecting socket failed
LoginActions.js:50 Logging in failed Cannot connect to the server

using https gives the same result.

Note, that when using http://192.168.1.10:5600/ for example, there is no issue login in. 
You can use it fine using direct IP in local network - but using domain and proxy you get the connecting socket error.

**Comment by maksis** [comment] 2017-05-11 14:51
@u2hub #205 wasn't an actual Websocket issues as it was caused by an application crash. You seem to be receiving an error code instead. Can you find anything useful from nginx's access logs?

**Comment by u2hub** [comment] 2017-05-12 16:42
Checked the error.log file - and nothing unusual there.
Doing the CTRL-SHIFT-J in Chrome, shows it occurring at:

`	var connectInternal = function connectInternal(resolve, reject, authenticationHandler) {
		var reconnectOnFailure = arguments.length > 3 && arguments[3] !== undefined ? arguments[3] : true;

		ws = new WebSocketImpl(options.url);

		var scheduleReconnect = function scheduleReconnect() {
			if (!reconnectOnFailure) {
				reject('Cannot connect to the server');
				return;
			}

			reconnectTimer = setTimeout(function () {
				logger.info('Socket reconnecting');
				connectInternal(resolve, reject, authenticationHandler, reconnectOnFailure);
			}, options.reconnectInterval * 1000);
		};

		ws.onopen = function () {
			logger.info('Socket connected');

			setSocketHandlers();
			authenticate(resolve, reject, authenticationHandler, scheduleReconnect);
		};

		ws.onerror = function (event) {
			logger.info('Connecting socket failed');
			scheduleReconnect();
		};
	};`

in the webpack:///./~/airdcpp-apisocket/dist/SocketBase.js   file

**Comment by maksis** [comment] 2017-05-12 17:37
`Error during WebSocket handshake: Unexpected response code: 400`

That strongly suggests, that an error is being returned by the server (either by nginx or the application itself). Do you have a nginx log with all proxied requests? As suggested in #225, you could also start the application with `--cdm-web` parameter and check the daemon console for error messages.

**Comment by maksis** [comment] 2017-05-12 17:40
Oh, and could paste your current application version (`airdcppd -v` in terminal)

**Comment by u2hub** [comment] 2017-05-12 17:44
Dear Maksis, I will read and try any suggestion.

Thanks for your quick responses!
This error was there though also with v 1.4.1 (The version before 2.0)

Application version  AirDC++w 2.0.1 x86_64
Web UI version  2.0.2
Web UI build date  May 7, 2017 10:36 PM
API version  1
API feature level  0
Started  3 days ago

I am using the gangefors image.

https://hub.docker.com/r/gangefors/airdcpp-webclient/

**Comment by u2hub** [comment] 2017-05-12 17:53
No idea if it helps, but let me repeat that I am able to log in good when using direct IP of the server it is running on. Username and password give no issue.

The Reverse Proxy from Synology works for many of the software I have installed without issue, you simply give post number either http or https with 80 or 443 respectfully and it works.

When I hinted on that it might be related to the error described above by PauliGrinder is the "/api/v1" error, which I also saw happening:

`SocketBase.js:190 WebSocket connection to 'ws://www.mywebsite.com/api/v1/' failed: Error during WebSocket handshake: Unexpected response code: 400`

**Comment by Kcchouette** [comment] 2017-05-12 17:58
Using https://airdcpp-web.github.io/docs/advanced/nginx-setup.html without other change (ok I only change http→https) is working for me

Because opening `location /airdcpp/` open the API too. did you try with the `/` after airdcpp for your first location?

**Comment by maksis** [comment] 2017-05-12 18:01
Hmm, maybe I should try it with nginx 1.11 (I have version 1.10)

**Comment by maksis** [comment] 2017-05-12 19:14
I tested the example config with nginx 1.12.0 and it worked just fine. I have no idea that what this is about if there is nothing in the server log.

**Comment by maksis** [comment] 2017-05-16 19:34
I'll close this to avoid confusing people with multiple config examples for the same task. I've also tested the example config with different version of nginx without issues, so the actual problem with it is not clear to me. However, feel free to open a new issue if the actual error information is available.

Some remarks:

- Don't remove trailing slashes from the example config
- Check the content of nginx's access and error logs (they typically start with `airdcpp.access.`)
- Don't use HTTPS when connecting to localhost as it's generally just waste of resources/latencies

**Closed by maksis** 2017-05-16 19:34 UTC
