### ISSUE TITLE
Queue tab - Sources error

### ISSUE THREAD

**Issue by c0r4ir** [airdcpp-web/airdcpp-webclient#372] opened 2020-11-03 17:11 UTC
The following Error occurs after clicking on Sources in the Queue tab. This issue was also present from webui version 2.8.0 onward.

Web UI has crashed with the following error: "Invariant Violation: Invalid user object in UserMenuDecorator: id and hub_url missing"

Please submit a bug report with the requested information (and the error message above) at the issue tracker.

### Current UI and client versions:

AirDC++w 2.9.0 x86_64
Browser: Google Chrome and Microsoft Edge

### Operating system: 

QNAP QTS 4.5.1.1461

### Steps to reproduce the issue:

Open Queue tab after a new download is added. Click "Sources" .

**Comment by maksis** [comment] 2020-11-03 17:17
Duplicate of https://github.com/airdcpp-web/airdcpp-webclient/issues/367

For some reason I still haven't been able to make that happen

**Closed by maksis** 2020-11-03 17:17 UTC
