### ISSUE TITLE
Problem to downloading filelist

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#61] opened 2016-01-28 20:47 UTC
I have an error between airdcpp-webclient and other software during the download of the filelist (Download pending). With ncdc, it's ok.

I don't really know how to debug that.

Here the console log:

```
62 DELETE hubs/v0/session/1/hub_user_view (no data) main.entry.js:83:24625
63 DELETE hubs/v0/session/1/listener/hub_counts_updated (no data) main.entry.js:83:24625
62 SUCCEED (no data) main.entry.js:83:24891
63 SUCCEED (no data) main.entry.js:83:24891
```

PS: same problem with aircnano

Edit: system config
```
Application version
AirDC++ w 0.13.3-46-g2698 x86_64 / 0.850
Web UI version 0.14.1
Web UI build date January 26, 2016 3:02 PM
```
I build the last version from github

**Comment by maksis** [comment] 2016-01-28 21:52
What are your connectivity settings? Are you using a different TLS port that is opened from the router?

**Comment by Kcchouette** [comment] 2016-01-28 21:54
I'm using 5601 port for https. Http is 0 (no port).
<br>Else my ipv4 is manual, and my ipv6 is disable.

**Comment by maksis** [comment] 2016-01-28 21:56
I'm interested in your IPv4 settings (especially the ports used by the client)

**Comment by Kcchouette** [comment] 2016-01-28 22:02
IPV4 setting is

```
 bind 0000 (any)
connectivity active mode
IP : my ip
update ip on startup checked
Don't allow hub/UPnP to override uchecked
```

My ports are

```
TCP (auto detected) 56256
UDP (auto detected) 56605
TLS/TCP (auto detected) 21206
Preferred port mapping interface (auto detected) MiniUPnP
```

**Comment by maksis** [comment] 2016-01-28 22:09
Are you absolutely sure that the TLS (TCP) port is accessible from the internet?

**Comment by Kcchouette** [comment] 2016-01-28 22:10
Yes.

50% is the filelist is downloaded

**Comment by maksis** [comment] 2016-01-28 22:13
> 50% is the filelist is downloaded

Half of the lists can be downloaded? With who are you having issues? Are you downloading via ADC or NMDC hubs?

**Comment by Kcchouette** [comment] 2016-01-28 22:14
No. I just that with 20 personn on the chan, 10 I can download the filelist, 10 I can't because of this bug

**Comment by maksis** [comment] 2016-01-28 22:17
Can you be more specific about the users and the clients from who you can't download and how are they different from the other users?

**Comment by maksis** [comment] 2016-01-28 22:42
I don't believe that this is a client bug because there shouldn't be compatibility issues with other clients (unless they use some very exotic clients, which is why I'd like to get more information). And do you have any other downloads running, possibly from those other users?

**Comment by Kcchouette** [comment] 2016-01-29 15:07
I'll past you a picture in the next day with my test.

Because of #62, I haven't any download running. Only download **finish** with airdcnano is present

**Comment by Kcchouette** [comment] 2016-01-29 18:26
![screenshot](https://cloud.githubusercontent.com/assets/3000936/12684173/90ff973a-c6bd-11e5-8c91-97d5081bb7d9.png)

Airdcnano and airdcpp-web are only on server because #60. I only show 'pending download'. 10 personn on hub, 3 failed.

I use airdcpp-web version https://github.com/airdcpp-web/airdcpp-webui/commit/f144de69f6fa2c3a5dca372732d614db1e503721 and https://github.com/airdcpp-web/airdcpp-webclient/commit/269828909bc5e134af68a76057944f9913a9e8ef .
@home is archlinux
@server is debian

**Comment by maksis** [comment] 2016-01-29 22:40
I will soon release a new version with transfer view. It will be easier to check transfer failures then.

ps. is "KO" a failure?

**Comment by Kcchouette** [comment] 2016-01-29 22:43
Ok.

yes, ok is "it works" and ko is "it fails".

Thanks

**Comment by maksis** [comment] 2016-01-31 15:22
Better test with the new version

**Comment by Kcchouette** [comment] 2016-01-31 18:27
User number 3 in my table seems ok with the new version. The two others, no, and no new log message is displaing.

**Comment by maksis** [comment] 2016-02-01 16:44
There are no fixes in the new version that could possibly fix connectivity issues. There's a new transfer view that will show more information about the connections.

**Comment by maksis** [comment] 2016-02-03 10:58
Seems like there are issues with most ncdc users when encrypted transfers are enabled

**Comment by maksis** [comment] 2016-02-03 11:32
https://dev.yorhel.nl/ncdc/bug/68

Possibly related to this?

**Comment by Kcchouette** [comment] 2016-02-03 16:50
Yes, it seems very similar.

I just change connectivity to passive on airdcpp; User 2 and User 3' filelists are showing.

And my ncdc @home my session are passive!

**Comment by maksis** [comment] 2016-02-03 17:20
ncdc generates its certificates with a non-unique common name which most likely caused the issue. Because of that, only transfers with the first ncdc user succeed and other ones failed. Such certificate errors should be ignored by https://github.com/airdcpp/airgit/commit/1315ddba649e4c5c32132976f3d0f0a1ca46aa44 and the fix will be available in the next release.

**Comment by maksis** [comment] 2016-02-03 22:40
Unfortunately that change doesn't make any difference. I should probably do some debugging with this.

**Comment by maksis** [comment] 2016-02-08 10:27
There's a workaround for this in version 0.16.2 (it will display such transfers as non-validated)

**Comment by Kcchouette** [comment] 2016-02-12 22:47
Yes, I can see filelist in the queue area.<br>For the problem, it shows a "Connection timeout" for the two filelist which doesn't works.

**Comment by maksis** [comment] 2016-02-12 23:05
I'm not able to reproduce your issue. I've tested the latest version with 10 different ncdc users and there haven't been any failures.

**Comment by Kcchouette** [comment] 2016-02-20 12:06
How can I help you?

**Comment by maksis** [comment] 2016-02-20 14:19
First you should upgrade to version 0.16.4.

If it doesn't work, I can't really help without having access to the hub or having the following information (or screenshot) about the failing users and your own clients from the user list: tags, IP addresses (v4 and v6). ``--cdm-client`` and ``--cdm-hub`` startup params would also help with troubleshooting but you need to understand the protocol commands then.

**Comment by Kcchouette** [comment] 2016-02-20 14:25
Ok, I'll try with 0.16.4.

I'm sorry, but I can't share with you this kind of informations :/<br>And I don't understand the protocol.

I'm hoping that's 0.16.4 will fix this bug.

**Comment by maksis** [comment] 2016-02-20 14:32
I doubt that your issue is fixed. You can also try external tools the check whether the remote user can be accessed with the provided IP and port and that they can access you.

I'll close this issue as the compatibility issue with ncdc has been fixed, but you can open a new issue if needed.

**Closed by maksis** 2016-02-20 14:32 UTC
Labels: bug
