### ISSUE TITLE
Web UI has crashed with TypeError: Cannot read properties of null (reading 'setRoot')

### ISSUE THREAD

**Issue by jahrock** [airdcpp-web/airdcpp-webclient#443] opened 2023-03-07 08:44 UTC
### Current UI and client versions:

Application version: AirDC++w 2.11.3 x86_64
Web UI version: 2.11.3
Web UI build date: December 2, 2022 8:27 PM
API version: 1
API feature level: 7
Started: 3 months ago
Active sessions: 1
Server threads: 8

OS: Ubuntu 22.10
Browser: Chrome version 110.0.5481.177 (Official Build) snap (64-bit)

### Operating system:

Linux

### Steps to reproduce the issue:

Visit https://webdemo.airdcpp.net/
Login with demo credentials
Navigate to Search
Navigate to Queue
Navigate to Home

Somewhere in between the Web UI throws **TypeError: Cannot read properties of null (reading 'setRoot')**

```
Crash details
TypeError: Cannot read properties of null (reading 'setRoot')
    at https://webdemo.airdcpp.net/js/760.06fe88831bf2e54f1ef5.chunk.js:2:116205
    at Js (https://webdemo.airdcpp.net/js/main.339947fcaa2c1af6139d.entry.js:2:2529308)
    at fl (https://webdemo.airdcpp.net/js/main.339947fcaa2c1af6139d.entry.js:2:2531377)
    at dl (https://webdemo.airdcpp.net/js/main.339947fcaa2c1af6139d.entry.js:2:2531217)
    at fl (https://webdemo.airdcpp.net/js/main.339947fcaa2c1af6139d.entry.js:2:2532166)
    at dl (https://webdemo.airdcpp.net/js/main.339947fcaa2c1af6139d.entry.js:2:2531217)
    at fl (https://webdemo.airdcpp.net/js/main.339947fcaa2c1af6139d.entry.js:2:2532166)
    at dl (https://webdemo.airdcpp.net/js/main.339947fcaa2c1af6139d.entry.js:2:2531217)
    at fl (https://webdemo.airdcpp.net/js/main.339947fcaa2c1af6139d.entry.js:2:2532166)
    at dl (https://webdemo.airdcpp.net/js/main.339947fcaa2c1af6139d.entry.js:2:2531217)
```

### Screenshots

![image](https://user-images.githubusercontent.com/1192502/223368438-352f007f-e761-4a6a-b97b-171f618cd2e6.png)

**Comment by maksis** [comment] 2023-03-07 08:55
Seems to be caused by https://github.com/schrodinger/fixed-data-table-2/issues/661

Fixed by updating the table library to the latest version

**Closed by maksis** 2023-03-07 08:55 UTC
Labels: bug
