### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by vestingz** [airdcpp-web/airdcpp-webclient#403] opened 2021-07-20 15:50 UTC
I am running AirDC++w 2.11.0 under Arch Linux (Linux 5.10.46-1-lts x86_64) in a screen session. 

Lately, airdcppd crashes after a few hours of uptime. I am not sure about the reasons and the coredumps attached ([#1](https://0x0.st/-VpW.txt), [#2](https://0x0.st/-Vp4.txt)) don't seem to help much more either. 

Is there a good way to debug this further? Thank you!

**Comment by maksis** [comment] 2021-07-20 16:23
Are you able to get anything more useful if you get the stacktrace with gdb according to https://github.com/airdcpp-web/airdcpp-webclient/blob/master/.github/CONTRIBUTING.md#application-freezesdeadlocks ? 

Looks like it's related to responding to a search so you could also run the application with the `--cdm-hub` parameter. It will then spam all incoming searches (and other hub commands) in the console. Try to catch the `BSCH` command that was received right before the application crashed.

**Comment by vestingz** [comment] 2021-07-21 06:31
Thank you for your answer! :)

I have yet to see another crash but was able to retrieve more info through systemd-coredump: `coredumpctl gdb PID`-> `thread apply all bt full`. The output is [here](https://0x0.st/-Vyr.txt). I hope that this is somewhat helpful? If not, I will wait for another crash and then try the method you were suggesting.

I will also look into running airdcppd with the parameter you mentioned.

**Comment by maksis** [comment] 2021-07-21 08:08
Unfortunately those logs don't show the exact code line where the crash happened, so I need something different

**Comment by vestingz** [comment] 2021-07-21 10:02
Alright, I will post with an update here as soon as it happened again 👍

**Comment by vestingz** [comment] 2021-07-23 17:13
So I had another crash, but I was unfortunately not able to follow the steps you suggested [here](https://github.com/airdcpp-web/airdcpp-webclient/issues/403#issuecomment-883525607), as the application does not freeze, but just exits.

I realized though that I had never attached the last console messages from before the crash, so here they are: https://0x0.st/-VCq.txt

**Comment by maksis** [comment] 2021-07-24 07:21
Using `--cdm-hub` would be a really good start as then you would know the crashing search query that could possibly be used to reproduce the crash without waiting....

**Comment by maksis** [comment] 2021-07-26 18:46
@vestingz did it stop crashing...? Version 2.11.1 will be released within the next few days, quite likely without a fix for this issue.

**Comment by maksis** [comment] 2021-07-27 15:01
[Version 2.11.1](http://airdcpp-web.github.io/2021/07/27/version-2.11.1.html) is out so you should switch to that one. Remember to refresh your share as mentioned in the release notes (if auto refresh is disabled).

**Comment by vestingz** [comment] 2021-07-27 15:27
> @vestingz did it stop crashing...? Version 2.11.1 will be released within the next few days, quite likely without a fix for this issue.

Yes, it is running just fine since I used `--cdm-hub` 😄

Thank you very much for the update! I will switch asap and let you know in this thread if the problem persists. Have a good week :)

**Comment by vestingz** [comment] 2021-07-30 18:43
Ok, I just had another crash with the last BSCH command before the crash being: `BSCH J43N TO1/659309858 GE0 ANmovies TY2`
The terminating message was the following: http://0x0.st/-WRX.txt

I would update the client now and run it again with `--cdm-hub`.

**Comment by maksis** [comment] 2021-07-30 18:48
You should try performing the same search with another client (you can ask someone else to do it if you don't have one, you can also join the dev hub). The search query is simply "movies" with type directory and minimum size of 0.

**Comment by maksis** [comment] 2021-08-06 03:51
Have you tried to reproduce the crash as suggested in the previous comment?

**Comment by maksis** [comment] 2021-08-22 14:17
@vestingz did the issue disappear?

**Comment by vestingz** [comment] 2021-08-22 22:33
> @vestingz did the issue disappear?

Judging from the service journal, not really - it still crashes every other day or so, but I mitigated by managing the daemon through a systemd service with `Restart = on-failure`. This just restarts the daemon after the crash. Sorry that I can't be of more help at this point :( Although the issue is not solved, I think this thread can be closed.

**Closed** 2021-08-23 08:03 UTC
Labels: incomplete
