### ISSUE TITLE
Ability to select files/folders to download in a file list and seach results

### ISSUE THREAD

**Issue by Ven1m** [airdcpp-web/airdcpp-webclient#439] opened 2023-01-14 15:37 UTC
Problem:
Quite often I would like to queue up many directories while browsing a filelist and download them to a selected directory matching my own directory structure.

Proposal:
Ability to first filter content in a directory then to select one, multiple or all matches using check boxes. The next action should be performed to all selected rows. For example download to a specified directory.

The same feature should be added to the ordinary search function as well.

**Comment by maksis** [comment] 2023-01-15 14:12
Duplicate of https://github.com/airdcpp-web/airdcpp-webclient/issues/90

**Closed by maksis** 2023-01-15 14:12 UTC
Labels: duplicate, enhancement (upvotes needed)
