### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by Flwk** [airdcpp-web/airdcpp-webclient#344] opened 2020-03-13 05:44 UTC
### Current UI and client versions:

AirDC++w 2.6.1
I use Chrome 80.0.3987.132

### Operating system:

The server i use is on  Debian 9 64 bits
### Steps to reproduce the issue:
So, it've been a long time i use the web client of AirDc, but when i reboot my server, and try to launch like usual, i have timed out error. The port is open, and i don't have any error on the server side. 

Do you know how can i debug this issue ? 

Sorry for my english, it's not my native language

Cordialy

**Comment by maksis** [comment] 2020-03-17 14:14
Did you check the help message at the bottom of "Settings" -> "Connectivity"? There are two links that might be helpful. I'd also recommend using the latest application version.

**Comment by Flwk** [comment] 2020-03-24 22:15
> Did you check the help message at the bottom of "Settings" -> "Connectivity"? There are two links that might be helpful. I'd also recommend using the latest application version.

I use it on a debian server, so i can only use the command line :'(

**Comment by maksis** [comment] 2020-03-25 07:52
Where do you get that timeout error...? When opening the Web UI in browser?

**Comment by Flwk** [comment] 2020-03-25 07:54
> Where do you get that timeout error...? When opening the Web UI in browser?

Yes

**Comment by maksis** [comment] 2020-03-25 07:59
Ah I thought that you meant file transfers. 

Is the UI accessible from the server where the app is running? You can try `wget http://localhost:5600` (or whichever port you are using) from the command line (it should produce error 404).

**Comment by Flwk** [comment] 2020-03-25 16:50
> Ah I thought that you meant file transfers.
> 
> Is the UI accessible from the server where the app is running? You can try `wget http://localhost:5600` (or whichever port you are using) from the command line (it should produce error 404).

```
--2020-03-25 17:49:22--  http://localhost:5600/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:5600... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-03-25 17:49:22 ERROR 404: Not Found.
```
I have this, but when i try to connect the Ui whit Chrome, i have a connection timed-out error

**Comment by maksis** [comment] 2020-03-25 16:55
How have you validated that the port is open? Have you used a port checker, such as https://www.yougetsignal.com/tools/open-ports/ ? Did you try the latest application version?

**Comment by Flwk** [comment] 2020-03-25 17:02
> How have you validated that the port is open? Have you used a port checker, such as https://www.yougetsignal.com/tools/open-ports/ ? Did you try the latest application version?

Yeah, i'v tried with this port checker, and it tell me that the port is open. 

I don't know how to update AirDC++w whit line command, i'valway did it with the Web Interface.

**Comment by maksis** [comment] 2020-03-25 17:06
> I don't know how to update AirDC++w with line command, i'valway did it with the Web Interface.

You can just replace the files and restart the application (it's not something that you can do from the Web UI).

You could also locate the config file `WebServer.xml` and see if there's is anything that could affect the connectivity (such as bind address)

**Comment by Flwk** [comment] 2020-03-25 17:14
I'v found some Logs, and i still don't know where is the problem : 

```
[2020-03-25 17:48] Connectivity (IPv4 & IPv6): Determining the best connectivity settings...
[2020-03-25 17:48] Connectivity (IPv4): Public IP address detected, selecting active mode with direct connection
[2020-03-25 17:48] Connectivity (IPv6): IPv6 connectivity has been disabled as no public IPv6 address was detected
[2020-03-25 17:48] Updating GeoIP database...
[2020-03-25 17:48] GeoIP database could not be updated
[2020-03-25 17:48] File list refresh initiated
```
I've done the update, and i'm now on AirDC++w 2.7.0, and i have the same problem

**Comment by maksis** [comment] 2020-03-25 17:20
Did you check the config file content? Based on your local wget test, the application seems to be available locally. If you can't access it remotely and there is no unusual config in WebServer.xml, can't think of anything in the application itself that could cause it. Of course you can try it without the old config files too, just to be sure.

**Comment by Flwk** [comment] 2020-03-25 17:24
> Did you check the config file content? Based on your local wget test, the application seems to be available locally. If you can't access it remotely and there is no unusual config in WebServer.xml, can't think of anything in the application itself that could cause it. Of course you can try it without the old config files too, just to be sure.

I'v try with new filw config files, and i can't access it. Do you know if it can be IPTables problem ? Or maybe Nginx ?

**Comment by maksis** [comment] 2020-03-25 17:27
Are you using it with nginx..? Yes, it can be the problem then. Nginx, iptables, anything is possible. It's difficult to say without knowing your system/network config.

**Comment by maksis** [comment] 2020-05-08 12:27
Were you able to solve it?

**Comment by Flwk** [comment] 2020-05-08 13:42
no it's not working

**Comment by maksis** [comment] 2020-08-19 18:14
I'm going to close the issue as there is no indication that issue is caused by AirDC++. I'd recommend trying to load the Web UI without nginx/iptables/other services that might prevent the access (maybe such services also have information in their own logs about the problem).

**Closed by maksis** 2020-08-19 18:14 UTC
Labels: question
