### ISSUE TITLE
User filters are applied in favorites tab

### ISSUE THREAD

**Issue by sbraz** [airdcpp-web/airdcpp-webclient#93] opened 2016-02-26 10:12 UTC
When filtering a user list and then editing an user, the filter previously used in the user list is applied to the favorites list.

**Comment by maksis** [comment] 2016-02-26 10:16
Please post required information for bug reports as per https://github.com/airdcpp-web/airdcpp-webclient/blob/master/ISSUES.md

**Comment by sbraz** [comment] 2016-02-26 10:17
Application version: AirDC++w 0.16.4 x86_64 / 0.850
Web UI version: 0.16.2
Browser: Firefox 44.0.2

**Comment by maksis** [comment] 2016-02-26 14:37
Is anyone else experiencing this issue?

**Comment by maksis** [comment] 2016-03-02 18:28
I noticed that Firefox actually tries to autocomplete your username in the filter field if you one saved for the site and you open the password dialog... quite creative way to detect a login form.

**Comment by maksis** [comment] 2016-03-02 18:34
Which makes this a duplicate of #100

**Closed by maksis** 2016-03-02 18:34 UTC
