### ISSUE TITLE
Excluded Paths Removed

### ISSUE THREAD

**Issue by dirtymurt** [airdcpp-web/airdcpp-webclient#375] opened 2020-11-16 13:03 UTC
My Excluded paths are removed after an update. I have to add them back in. I think because of where they are stored that file is being over-written. Be better to have their own file that does not get updated.

**Comment by maksis** [comment] 2020-11-16 13:29
Please post the information that was requested in the issue template (and issue reporting instructions)

**Comment by maksis** [comment] 2020-11-22 14:24
Closing as there isn't enough information to do anything (how did you update, what are the versions involved and so on). Your config files don't get overwritten during the upgrade so the issue is related to something else.

**Closed by maksis** 2020-11-22 14:24 UTC
Labels: incomplete
