### ISSUE TITLE
Web Interface not accessible after ufw enabled

### ISSUE THREAD

**Issue by vestingz** [airdcpp-web/airdcpp-webclient#161] opened 2016-06-14 16:17 UTC
Web Interface was not accessible just fine until i enabled ufw with respective ports (5600/5601) allowed on both ipv4 and ipv6 stack. Connection attempts were not refused but finally resolved in an timeout. Other local services continued working just fine. Disabling ufw and rebooting solved this issue.
Running ubuntu 16.04.

**Comment by maksis** [comment] 2016-06-16 19:37
So you had other applications with ports forwarded as well and this was the only one causing problems? Did you use IPv4 or IPv6 when connecting to the UI (and have you tried both)?

**Comment by vestingz** [comment] 2016-06-16 22:14
Yes, exactly. Next to a working OpenSSH-Service i had a Tomcat-Server listening on 8080, both working as expected while not being able to access the web interface. Connection attempts to other (closed) ports were immediatly refused, only 5600/5601 had a timeout. I tried hostname:port, IPv4:port and IPv4-mapped IPv6:port. Also i disabled the IPv6 stack (before i found out that the web interface only listens at IPv6). Did a re-install as well as clean re-install, tried other ports as well. On a nmap scan the respective ports showed as 'filtered', if that matters.
Only after disabling ufw and rebooting the web interface of airdcppd works flawlessly.
OT: This project is great beyond words, thank you very much for all your hard work! :)

**Comment by maksis** [comment] 2016-06-17 08:15
I managed to reproduce the issue and it seems to be related to https://github.com/zaphoyd/websocketpp/issues/549 as were there messages about SYN flood in the syslog.

I committed the recommended workaround and it's available in the develop branch.

**Closed by maksis** 2016-06-17 08:15 UTC
Labels: question

**Comment by vestingz** [comment] 2016-06-27 07:58
Thank you very much. Working like a charm now.
