### ISSUE TITLE
Favorites not saved after restart

### ISSUE THREAD

**Issue by tombs007** [airdcpp-web/airdcpp-webclient#208] opened 2016-12-16 23:05 UTC
Every time airdcppd stops and is started again all my hubs listed in favorites is gone. I have to re-enter them all again.

Settings are being saved but not favorites.

Is there a file that can be set to prevent this?

### Current UI and client versions:

AirDC++w 1.4.0 x86_64
Web UI version
1.4.0
Web UI build date
December 9, 2016 5:12 AM

### Steps to reproduce the issue:

Stop and start airdcppd

**Comment by maksis** [comment] 2016-12-16 23:34
Could you post the full console output from the daemon after initiating shutdown?

**Comment by tombs007** [comment] 2016-12-17 00:04
Shutdown:

[2016-12-16 18:59:37] [disconnect] Failed: TLS Short Read
[2016-12-16 18:59:38] [connect] WebSocket Connection [::f]:60800 v13 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36" / 101
[2016-12-16 18:59:39] [fatal] error in handle_read_handshake: TLS Short Read
[2016-12-16 18:59:39] [disconnect] Failed: TLS Short Read
[2016-12-16 18:59:40] [connect] HTTP Connection [::ffff:76.182.43.246]:60802 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36" /js/home.7a6bcad72ff5a815866c.chunk.js 200
[2016-12-16 18:59:41] [disconnect] Failed: HTTP connection ended
[2016-12-16 18:59:41] [fatal] error in handle_read_handshake: TLS Short Read
[2016-12-16 18:59:41] [disconnect] Failed: TLS Short Read
[2016-12-16 18:59:41] [connect] HTTP Connection [::ff]:60807 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36" /images/AirDCPlusPlus.d2a0895612b6cf69ccdac84947d293e2.png 200
[2016-12-16 18:59:46] [disconnect] Failed: HTTP connection ended
[2016-12-16 19:00:01] [info] asio async_shutdown error: asio.ssl:336130329 (decryption failed or bad record mac)
[2016-12-16 19:00:01] [disconnect] Disconnect close local:[1000] remote:[1005]
[2016-12-16 19:00:51] [info] handle_accept error: Operation canceled
[2016-12-16 19:00:51] [info] Stopping acceptance of new connections because the underlying transport is no longer listening.
Saving hash data
Saving the share cache
Closing connections
Saving settings
Shutting down.

Startup:
Starting.
.Loading Hash database
Loading Download queue
Loading Shared files
Loading Country information
Starting web server.
AirDC++w 1.4.0 running, press ctrl-c to exit...
HTTP port: 0, HTTPS port: 5601
[2016-12-16 19:02:17] [fatal] error in handle_read_handshake: TLS Short Read
[2016-12-16 19:02:17] [disconnect] Failed: TLS Short Read
[2016-12-16 19:02:18] [connect] HTTP Connection [::ffff:]:60823 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36" /login 200
[2016-12-16 19:02:18] [disconnect] Failed: HTTP connection ended
[2016-12-16 19:02:18] [fatal] error in handle_read_handshake: TLS Short Read
[2016-12-16 19:02:18] [disconnect] Failed: TLS Short Read
[2016-12-16 19:02:22] [connect] HTTP Connection [::ffff]:60825 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36" /js/main.ae3b9cca1f415c65027f.entry.js 200
[2016-12-16 19:02:23] [disconnect] Failed: HTTP connection ended
[2016-12-16 19:02:23] [fatal] error in handle_read_handshake: TLS Short Read
[2016-12-16 19:02:23] [fatal] error in handle_read_handshake: TLS Short Read
[2016-12-16 19:02:23] [disconnect] Failed: TLS Short Read
[2016-12-16 19:02:23] [disconnect] Failed: TLS Short Read

**Comment by maksis** [comment] 2016-12-17 08:56
I'm unable to reproduce the issue. Can you provide the exact steps for reproducing this issue with a clean application instance? What is your operating system?

**Comment by tombs007** [comment] 2016-12-18 00:26
Very easy to reproduce.
-Start airdcppd with tmux
-Login to web interface
-Open Favorites
-Add a new hub
-Connect to the hub
-Logout of the web interface
-Stop the application, ctrl-c
-Restart airdccpd in tmux
-Login to the web interface
-Navigate to favorties
-All previously added hubs gone.

Compiled/Running on Debian 8.6, server is running in a remote location.

Where are the favorites stored? I see a Recents.xml in my .airdccpd directory.

**Comment by tombs007** [comment] 2016-12-18 00:29
Performed a ctrl-c to close the application:

^C[2016-12-17 19:25:43] [info] handle_accept error: Operation canceled
[2016-12-17 19:25:43] [info] Stopping acceptance of new connections because the underlying transport is no longer listening.
[2016-12-17 19:25:43] [info] asio async_shutdown error: asio.ssl:336462100 (uninitialized)
[2016-12-17 19:25:43] [disconnect] Failed: Operation canceled
0
pid: 23882
Collecting crash information, please wait...
[2016-12-17 19:25:43] [info] handle_read_frame error: websocketpp.transport:10 (A transport action was requested after shutdown)
[2016-12-17 19:25:43] [disconnect] Disconnect close local:[1006,A transport action was requested after shutdown] remote:[1001,Shutting down]
airdcppd in function cow::StackTrace::generate_frames() in file /home/tombs/airdcpp-webclient/airdcppd/stacktrace.cpp:44 [0x413193]
airdcppd in function __copy_move_a2<false, __gnu_cxx::__normal_iterator<cow::StackFrame*, std::vector<cow::StackFrame> >, std::ostream_iterator<cow::StackFrame> > in file /usr/include/c++/4.9/bits/stl_algobase.h:434 [0x41b68a]
airdcppd in function installHandler()::{lambda()#1}::_FUN() in file main.cpp:0 [0x41ba6b]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6 in function [unknown] [0x7f3604cc7bb6]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6 in function [unknown] [0x7f3604cc7c01]
/usr/local/lib/libairdcpp-webapi.so.1.4.0 in function webserver::WebSocket::sendPlain(nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator> const&) [0x7f3605bd1982]
/usr/local/lib/libairdcpp-webapi.so.1.4.0 in function webserver::SubscribableApiModule::send(nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator> const&) [0x7f3605c673d6]
/usr/local/lib/libairdcpp-webapi.so.1.4.0 in function webserver::SubscribableApiModule::send(std::string const&, nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator> const&) [0x7f3605c68847]
/usr/local/lib/libairdcpp-webapi.so.1.4.0 in function webserver::HashApi::onTimer() [0x7f3605cb8ba4]
/usr/local/lib/libairdcpp-webapi.so.1.4.0 in function webserver::Timer::runTask() [0x7f3605b871c9]
/usr/local/lib/libairdcpp-webapi.so.1.4.0 in function webserver::ApiModule::asyncRunWrapper(std::function<void ()> const&, unsigned int) [0x7f3605c67357]
/usr/local/lib/libairdcpp-webapi.so.1.4.0 in function webserver::Timer::tick(boost::system::error_code const&, std::function<void (std::function<void ()> const&)> const&, webserver::Timer*) [0x7f3605b8725e]
/usr/local/lib/libairdcpp-webapi.so.1.4.0 in function boost::asio::detail::wait_handler<std::_Bind<void (*(std::_Placeholder<1>, std::function<void (std::function<void ()> const&)>, webserver::Timer*))(boost::system::error_code const&, std::function<void (std::function<void ()> const&)> const&, webserver::Timer*)> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) [0x7f3605b69cef]
/usr/local/lib/libairdcpp-webapi.so.1.4.0 in function boost::asio::detail::task_io_service::run(boost::system::error_code&) [0x7f3605b7c2e1]
/usr/local/lib/libairdcpp-webapi.so.1.4.0 in function boost::asio::io_service::run() [0x7f3605b7cd76]
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.55.0 in function [unknown] [0x7f3603716aea]
/lib/x86_64-linux-gnu/libpthread.so.0 in function [unknown] [0x7f36057dd0a4]
/lib/x86_64-linux-gnu/libc.so.6 in function [unknown] [0x7f36049a662d]

Exception info to be posted on the bug tracker has also been saved in /home/tombs/.airdc++/exceptioninfo.txt
Press enter to continue

**Comment by maksis** [comment] 2016-12-18 10:28
This is now fixed in the develop branch. I'll release a new version soon.

**Closed by maksis** 2016-12-18 10:28 UTC
Labels: bug

**Comment by tombs007** [comment] 2016-12-18 14:45
Thanks, I'll build the development branch.

**Comment by maksis** [comment] 2016-12-18 20:05
1.4.1 is now available as well. That crash is related to something else so it would be great if you opened a new issue for it.
